# Welcome to Serverless!
service: aws-nodejs # NOTE: update this with your service name
app: krapiva-org
tenant: alexeiaccio

provider:
  name: aws
  runtime: nodejs8.10
  cfnRole: ${env:CFN_ROLE}

functions:
  subscribe:
    handler: handler.subscribe
    events:
      - http: GET subscribe
  counter:
    handler: handler.counter
    events:
      - http: GET counter
  get:
    handler: handler.get
    events:
      - http: GET get

plugins:
  - serverless-offline
  - serverless-dotenv-plugin